import { Resend } from "resend";
import nodemailer from "nodemailer";

const resendApiKey = process.env.RESEND_API_KEY;
export const resend = resendApiKey ? new Resend(resendApiKey) : null;

// SMTP fallback transporter (e.g., Gmail with App Password, custom SMTP)
const smtpHost = process.env.SMTP_HOST;
const smtpPort = Number(process.env.SMTP_PORT) || 587;
const smtpUser = process.env.SMTP_USER;
const smtpPass = process.env.SMTP_PASS;

const smtpTransporter = (smtpHost && smtpUser && smtpPass)
  ? nodemailer.createTransport({
      host: smtpHost,
      port: smtpPort,
      secure: smtpPort === 465,
      auth: {
        user: smtpUser,
        pass: smtpPass,
      },
    })
  : null;

export async function sendLeadEmailNotification(lead: {
  id: string;
  clientName: string;
  clientEmail?: string | null;
  clientPhone?: string | null;
  loadingPort?: string | null;
  dischargePort?: string | null;
  cargoType?: string | null;
  cargoVolume?: string | null;
  comment?: string | null;
  vesselName?: string | null;
}) {
  const recipient = process.env.NOTIFICATION_EMAIL || "artemkudliuk@gmail.com";
  console.log(`[EMAIL NOTIFICATION] Processing lead notification for: ${recipient} | Client: ${lead.clientName}`);

  const htmlContent = `
    <div style="font-family: Arial, sans-serif; max-width: 600px; margin: 0 auto; padding: 20px; border: 1px solid #e0e0e0; border-radius: 8px; background: #ffffff;">
      <div style="background: #1e1e1e; padding: 16px; border-radius: 6px; text-align: center;">
        <h2 style="color: #c89b3c; margin: 0; font-size: 20px; text-transform: uppercase; letter-spacing: 1px;">DANAMIRA SHIPPING LTD</h2>
        <p style="color: #ffffff; margin: 4px 0 0 0; font-size: 12px; letter-spacing: 2px;">NEW INBOUND FREIGHT INQUIRY</p>
      </div>
      
      <div style="padding: 20px 0;">
        <table style="width: 100%; border-collapse: collapse; font-size: 14px;">
          <tr><td style="padding: 8px 0; color: #666; width: 140px;">Client Name:</td><td style="padding: 8px 0; font-weight: bold; color: #111;">${lead.clientName}</td></tr>
          ${lead.clientEmail ? `<tr><td style="padding: 8px 0; color: #666;">Email:</td><td style="padding: 8px 0; color: #111;"><a href="mailto:${lead.clientEmail}">${lead.clientEmail}</a></td></tr>` : ""}
          ${lead.clientPhone ? `<tr><td style="padding: 8px 0; color: #666;">Phone:</td><td style="padding: 8px 0; color: #111;">${lead.clientPhone}</td></tr>` : ""}
          ${lead.vesselName ? `<tr><td style="padding: 8px 0; color: #666;">Target Vessel:</td><td style="padding: 8px 0; color: #c89b3c; font-weight: bold;">${lead.vesselName}</td></tr>` : ""}
          ${lead.loadingPort || lead.dischargePort ? `<tr><td style="padding: 8px 0; color: #666;">Route:</td><td style="padding: 8px 0; color: #111;">${lead.loadingPort || "?"} &rarr; ${lead.dischargePort || "?"}</td></tr>` : ""}
          ${lead.cargoType || lead.cargoVolume ? `<tr><td style="padding: 8px 0; color: #666;">Cargo:</td><td style="padding: 8px 0; color: #111;">${lead.cargoType || "N/A"} (${lead.cargoVolume || "N/A"})</td></tr>` : ""}
          ${lead.comment ? `<tr><td style="padding: 8px 0; color: #666; vertical-align: top;">Comment:</td><td style="padding: 8px 0; color: #333; background: #f9f9f9; padding: 10px; border-radius: 4px;">${lead.comment}</td></tr>` : ""}
        </table>
      </div>
      
      <div style="text-align: center; padding-top: 16px; border-top: 1px solid #eeeeee;">
        <p style="font-size: 11px; color: #888888; margin: 0;">This email was automatically generated by Danamira CMS.</p>
      </div>
    </div>
  `;

  // 1. Try Resend if configured
  if (resend) {
    try {
      await resend.emails.send({
        from: "Danamira Inquiries <onboarding@resend.dev>",
        to: [recipient],
        subject: `[New Lead] ${lead.clientName} - ${lead.cargoType || "Freight Request"}`,
        html: htmlContent,
      });
      console.log(`[EMAIL SUCCESS - Resend] Sent to ${recipient}`);
      return;
    } catch (err) {
      console.error("[EMAIL ERROR - Resend]", err);
    }
  }

  // 2. Try SMTP if configured
  if (smtpTransporter) {
    try {
      await smtpTransporter.sendMail({
        from: `"${process.env.EMAIL_SENDER_NAME || 'Danamira Shipping'}" <${smtpUser}>`,
        to: recipient,
        subject: `[New Lead] ${lead.clientName} - ${lead.cargoType || "Freight Request"}`,
        html: htmlContent,
      });
      console.log(`[EMAIL SUCCESS - SMTP] Sent to ${recipient}`);
      return;
    } catch (err) {
      console.error("[EMAIL ERROR - SMTP]", err);
    }
  }

  // 3. No email transport configured note
  console.log(`[EMAIL NOTE] No email provider configured (RESEND_API_KEY or SMTP_HOST/SMTP_USER/SMTP_PASS). Lead saved in PostgreSQL database only.`);
}
