import { Resend } from "resend";

const apiKey = process.env.RESEND_API_KEY;
export const resend = apiKey ? new Resend(apiKey) : null;

export async function sendLeadEmailNotification(lead: {
  id: string;
  clientName: string;
  clientEmail?: string | null;
  clientPhone?: string | null;
  loadingPort?: string | null;
  dischargePort?: string | null;
  cargoType?: string | null;
  cargoVolume?: string | null;
  comment?: string | null;
  vesselName?: string | null;
}) {
  const recipient = process.env.NOTIFICATION_EMAIL;
  if (!resend || !recipient) {
    console.log("Resend API key or NOTIFICATION_EMAIL not set, skipping email.");
    return;
  }

  try {
    const htmlContent = `
      <div style="font-family: Arial, sans-serif; max-width: 600px; margin: 0 auto; padding: 20px; border: 1px solid #e0e0e0; border-radius: 8px; background: #ffffff;">
        <div style="background: #1e1e1e; padding: 16px; border-radius: 6px; text-align: center;">
          <h2 style="color: #c89b3c; margin: 0; font-size: 20px; text-transform: uppercase; letter-spacing: 1px;">Danamira Shipping Ltd</h2>
          <p style="color: #ffffff; margin: 4px 0 0 0; font-size: 12px; letter-spacing: 2px;">NEW FREIGHT INQUIRY</p>
        </div>
        
        <div style="padding: 20px 0;">
          <table style="width: 100%; border-collapse: collapse; font-size: 14px;">
            <tr><td style="padding: 8px 0; color: #666; width: 140px;">Client Name:</td><td style="padding: 8px 0; font-weight: bold; color: #111;">${lead.clientName}</td></tr>
            ${lead.clientEmail ? `<tr><td style="padding: 8px 0; color: #666;">Email:</td><td style="padding: 8px 0; color: #111;"><a href="mailto:${lead.clientEmail}">${lead.clientEmail}</a></td></tr>` : ""}
            ${lead.clientPhone ? `<tr><td style="padding: 8px 0; color: #666;">Phone:</td><td style="padding: 8px 0; color: #111;">${lead.clientPhone}</td></tr>` : ""}
            ${lead.vesselName ? `<tr><td style="padding: 8px 0; color: #666;">Vessel:</td><td style="padding: 8px 0; color: #c89b3c; font-weight: bold;">${lead.vesselName}</td></tr>` : ""}
            ${lead.loadingPort || lead.dischargePort ? `<tr><td style="padding: 8px 0; color: #666;">Route:</td><td style="padding: 8px 0; color: #111;">${lead.loadingPort || "?"} &rarr; ${lead.dischargePort || "?"}</td></tr>` : ""}
            ${lead.cargoType || lead.cargoVolume ? `<tr><td style="padding: 8px 0; color: #666;">Cargo:</td><td style="padding: 8px 0; color: #111;">${lead.cargoType || "N/A"} (${lead.cargoVolume || "N/A"})</td></tr>` : ""}
            ${lead.comment ? `<tr><td style="padding: 8px 0; color: #666; vertical-align: top;">Comment:</td><td style="padding: 8px 0; color: #333; background: #f9f9f9; padding: 10px; border-radius: 4px;">${lead.comment}</td></tr>` : ""}
          </table>
        </div>
        
        <div style="text-align: center; padding-top: 16px; border-top: 1px solid #eeeeee;">
          <p style="font-size: 11px; color: #888888; margin: 0;">This email was automatically generated by Danamira CMS.</p>
        </div>
      </div>
    `;

    await resend.emails.send({
      from: "Danamira Inquiries <notifications@danamirashipping.com>",
      to: [recipient],
      subject: `[New Lead] ${lead.clientName} - ${lead.cargoType || "Freight Request"}`,
      html: htmlContent,
    });
  } catch (err) {
    console.error("Failed to send lead email notification:", err);
  }
}
