const globalForData = globalThis as unknown as {
  _sampleVessels?: any[];
  _sampleLeads?: any[];
  _samplePages?: any[];
  _sampleBranches?: any[];
};

const initialSampleVessels = [
  {
    id: "vessel-molpadia",
    imoNumber: "9613616",
    name: {
      en: "MV MOLPADIA",
      ua: "Т/Х МОЛПАДІЯ",
      ru: "Т/Х МОЛПАДИЯ",
    },
    type: "bulk_carrier",
    status: "available",
    charterRateUsd: "8200.00",
    salePriceUsd: "5900000.00",
    priceOnRequest: false,
    currentLocation: "Mediterranean / Black Sea",
    tradingArea: "Mediterranean, Black Sea, Continent, Baltic",
    dwt: 6408,
    teu: 390,
    cubicCapacity: "8950.00",
    yearBuilt: 2014,
    flag: "Antigua & Barbuda",
    loa: "108.20",
    beam: "18.20",
    draft: "6.70",
    maxSpeed: "13.00",
    ecoSpeed: "11.00",
    classSociety: "DNV",
    description: {
      en: "Modern general cargo vessel built in 2014, 6,408 DWT with 2 Holds / 2 Hatches (2HO/2HA). Geared with 2x 30MT cranes. Fully equipped for agricultural bulk, steel products, project cargo, and solid fertilizers.",
      ua: "Сучасне судно генеральних вантажів 2014 року побудови, дедвейт 6,408 MT, 2 трюми / 2 люки (2HO/2HA), крани 2x 30 MT.",
      ru: "Современное судно генеральных грузов 2014 года постройки, дедвейт 6,408 MT, 2 трюма / 2 люка (2HO/2HA), краны 2x 30 MT.",
    },
    deckEquipment: {
      en: "2x 30MT SWL Electro-Hydraulic Cranes, hydraulic folding hatch covers (2HO/2HA)",
      ua: "2x 30MT електрогідравлічні крани, гідравлічні люкові закриття (2HO/2HA)",
      ru: "2x 30MT электрогидравлические краны, гидравлические люковые закрытия (2HO/2HA)",
    },
    coverImageUrl: "/fleet/molpadia/MV_MOLPADIA__PHOTO.jpg",
    isFeatured: true,
    createdAt: new Date().toISOString(),
    media: [
      {
        id: "m-mol-cover",
        url: "/fleet/molpadia/MV_MOLPADIA__PHOTO.jpg",
        type: "photo" as const,
        filename: "MV_MOLPADIA__PHOTO.jpg",
        sortOrder: 0,
        isCover: true,
      },
      {
        id: "m-mol-1",
        url: "/fleet/molpadia/Photo-1.jpg",
        type: "photo" as const,
        filename: "Photo-1.jpg",
        sortOrder: 1,
        isCover: false,
      },
      {
        id: "m-mol-2",
        url: "/fleet/molpadia/Photo-2.jpg",
        type: "photo" as const,
        filename: "Photo-2.jpg",
        sortOrder: 2,
        isCover: false,
      },
      {
        id: "m-mol-3",
        url: "/fleet/molpadia/Photo-3.jpg",
        type: "photo" as const,
        filename: "Photo-3.jpg",
        sortOrder: 3,
        isCover: false,
      },
      {
        id: "m-mol-4",
        url: "/fleet/molpadia/Photo-4.jpg",
        type: "photo" as const,
        filename: "Photo-4.jpg",
        sortOrder: 4,
        isCover: false,
      },
      {
        id: "m-mol-5",
        url: "/fleet/molpadia/Photo-5.jpg",
        type: "photo" as const,
        filename: "Photo-5.jpg",
        sortOrder: 5,
        isCover: false,
      },
      {
        id: "m-mol-6",
        url: "/fleet/molpadia/Photo-6.jpg",
        type: "photo" as const,
        filename: "Photo-6.jpg",
        sortOrder: 6,
        isCover: false,
      },
      {
        id: "m-mol-ga",
        url: "/fleet/molpadia/2_GA-PLAN.pdf",
        type: "pdf" as const,
        filename: "GA-PLAN_MV_MOLPADIA.pdf",
        sortOrder: 7,
        isCover: false,
      },
    ],
  },
  {
    id: "vessel-metanira",
    imoNumber: "9584724",
    name: {
      en: "MV METANIRA",
      ua: "Т/Х МЕТАНІРА",
      ru: "Т/Х МЕТАНИРА",
    },
    type: "bulk_carrier",
    status: "available",
    charterRateUsd: "8700.00",
    salePriceUsd: "6400000.00",
    priceOnRequest: false,
    currentLocation: "Port of Motril, Spain",
    tradingArea: "Mediterranean, Black Sea, Continent, West Africa",
    dwt: 7200,
    teu: 440,
    cubicCapacity: "9650.00",
    yearBuilt: 2012,
    flag: "Liberia",
    loa: "111.40",
    beam: "18.60",
    draft: "6.95",
    maxSpeed: "13.20",
    ecoSpeed: "11.20",
    classSociety: "Lloyd's Register",
    description: {
      en: "Geared dry bulk and general cargo carrier, 7,200 DWT. Box-shaped holds with 2HO / 2HA. Equipped with 2x 30MT cranes, suitable for heavy bulk minerals, fertilizers, steel products, and grain.",
      ua: "Судно генеральних та навалювальних вантажів 7,200 DWT, 2 трюми / 2 люки, крани 2x 30 MT.",
      ru: "Судно генеральных и навалочных грузов 7,200 DWT, 2 трюма / 2 люка, краны 2x 30 MT.",
    },
    deckEquipment: {
      en: "2x 30MT SWL Electro-Hydraulic Cranes, hydraulic folding hatch covers (2HO/2HA)",
      ua: "2x 30MT крани, гідравлічні люкові закриття",
      ru: "2x 30MT краны, гидравлические люковые закрытия",
    },
    coverImageUrl: "/fleet/metanira/PHOTO__MV_METANIRA.JPG",
    isFeatured: true,
    createdAt: new Date().toISOString(),
    media: [
      {
        id: "m-met-cover",
        url: "/fleet/metanira/PHOTO__MV_METANIRA.JPG",
        type: "photo" as const,
        filename: "PHOTO__MV_METANIRA.JPG",
        sortOrder: 0,
        isCover: true,
      },
      {
        id: "m-met-1",
        url: "/fleet/metanira/IMG_3293_800_600.JPG",
        type: "photo" as const,
        filename: "Deck_Port_View.JPG",
        sortOrder: 1,
        isCover: false,
      },
      {
        id: "m-met-2",
        url: "/fleet/metanira/IMG_3300_800_600.JPG",
        type: "photo" as const,
        filename: "Cranes_Structure.JPG",
        sortOrder: 2,
        isCover: false,
      },
      {
        id: "m-met-3",
        url: "/fleet/metanira/IMG_3305_800_600.JPG",
        type: "photo" as const,
        filename: "Cargo_Hold_Overview.JPG",
        sortOrder: 3,
        isCover: false,
      },
      {
        id: "m-met-4",
        url: "/fleet/metanira/IMG_3310_800_600.JPG",
        type: "photo" as const,
        filename: "Bow_Profile.JPG",
        sortOrder: 4,
        isCover: false,
      },
      {
        id: "m-met-5",
        url: "/fleet/metanira/IMG_3318_800_600.JPG",
        type: "photo" as const,
        filename: "Bridge_Nav_Deck.JPG",
        sortOrder: 5,
        isCover: false,
      },
      {
        id: "m-met-ga",
        url: "/fleet/metanira/1_GA_PLAN.pdf",
        type: "pdf" as const,
        filename: "GA-PLAN_MV_METANIRA.pdf",
        sortOrder: 6,
        isCover: false,
      },
      {
        id: "m-met-desc",
        url: "/fleet/metanira/Vessel_Description__METANIRA.png",
        type: "photo" as const,
        filename: "Vessel_Description__METANIRA.png",
        sortOrder: 7,
        isCover: false,
      },
    ],
  },
];

export const sampleVessels: any[] =
  globalForData._sampleVessels ||
  (globalForData._sampleVessels = initialSampleVessels);

const initialSampleLeads = [
  {
    id: "lead-001",
    status: "new",
    clientName: "AgroTrans Logistics BV",
    clientPhone: "+31 10 4455667",
    clientEmail: "chartering@agrotrans.nl",
    clientWhatsapp: "+31 6 12345678",
    clientTelegram: "@agrotrans_charter",
    loadingPort: "Port of Odesa (UA)",
    dischargePort: "Port of Ravenna (IT)",
    cargoType: "bulk",
    cargoVolume: "6,400 MT Wheat",
    vesselId: "vessel-molpadia",
    comment: "Prompt laycan window next week. Need geared vessel (MV MOLPADIA or sister) with 2x30t cranes.",
    sourcePage: "/routes/black-sea-grain-freight",
    createdAt: new Date(Date.now() - 3600000 * 2).toISOString(),
    vessel: sampleVessels[0],
  },
  {
    id: "lead-002",
    status: "in_progress",
    clientName: "Hellenic Steel Exports Ltd",
    clientPhone: "+30 210 9988776",
    clientEmail: "ops@hellenicsteel.gr",
    loadingPort: "Port of Motril (ES)",
    dischargePort: "Port of Alexandria (EG)",
    cargoType: "breakbulk",
    cargoVolume: "6,800 MT Steel Coils & Rebars",
    vesselId: "vessel-metanira",
    comment: "MV METANIRA fixture inspection requested. Please provide GA-plan and confirmation of crane SWL.",
    sourcePage: "landing-page",
    createdAt: new Date(Date.now() - 3600000 * 18).toISOString(),
    vessel: sampleVessels[1],
  },
  {
    id: "lead-003",
    status: "completed",
    clientName: "Black Sea Minerals LLC",
    clientPhone: "+380 48 7112233",
    clientEmail: "logistics@bs-minerals.com",
    loadingPort: "Port of Constanta (RO)",
    dischargePort: "Port of Mersin (TR)",
    cargoType: "bulk",
    cargoVolume: "5,000 MT Fertilizer",
    comment: "Fixture successfully agreed and signed. Charter in progress.",
    sourcePage: "landing-page",
    createdAt: new Date(Date.now() - 3600000 * 72).toISOString(),
  },
];

export const sampleLeads: any[] =
  globalForData._sampleLeads ||
  (globalForData._sampleLeads = initialSampleLeads);

export const samplePages = [
  {
    id: "page-home",
    slug: "index.html",
    pageName: "Home Page",
    status: "published",
    includeInNav: true,
    title: {
      en: "Danamira Shipping Ltd | International Maritime Logistics & Managed Fleet",
      ua: "Danamira Shipping Ltd | Міжнародна морська логістика та флот",
      ru: "Danamira Shipping Ltd | Международная морская логистика и флот",
    },
    metaDescription: {
      en: "Danamira Shipping Ltd — international maritime freight carrier and technical ship manager. Dry bulk, general cargo, and direct chartering across Mediterranean and Black Sea.",
      ua: "Danamira Shipping Ltd — міжнародний морський перевізник та технічний менеджмент флоту. Суховантажі та чартеринг.",
      ru: "Danamira Shipping Ltd — международный морской перевозчик и технический менеджмент флота. Сухогрузы и чартеринг.",
    },
    content: {
      en: "<h1>Integrated Maritime Logistics &amp; Fleet Operations</h1><p><strong>DANAMIRA SHIPPING LTD</strong> is an independent international ship-management carrier and freight operator. We provide geared dry bulk and general cargo transportation across the Mediterranean Sea, Black Sea, European Continent, and West Africa.</p><h2>Direct Fleet Chartering &amp; Fixtures</h2><p>Our modern geared general cargo carriers (<strong>MV MOLPADIA</strong>, <strong>MV METANIRA</strong>) are equipped with 2x 30MT electro-hydraulic cranes and box-shaped holds, perfectly suited for grain exports, bulk fertilizers, steel products, and heavy project cargoes.</p><h2>Key Operational Strengths</h2><ul><li><strong>24/7 Operational Support:</strong> Continuous chartering desk and live technical vessel monitoring.</li><li><strong>Port &amp; Route Versatility:</strong> Direct access to shallow drafts and regional grain river/sea terminals.</li><li><strong>Strict Safety Framework:</strong> Full compliance with IMO, ISM Code, and ISPS maritime security regulations.</li></ul>",
      ua: "",
      ru: "",
    },
    createdAt: new Date().toISOString(),
  },
  {
    id: "page-fleet",
    slug: "fleet.html",
    pageName: "Managed Fleet",
    status: "published",
    includeInNav: true,
    title: {
      en: "Managed Fleet & Technical Specifications | Danamira Shipping",
      ua: "Флот в управлінні та технічні специфікації | Danamira",
      ru: "Флот в управлении и технические спецификации | Danamira",
    },
    metaDescription: {
      en: "Explore Danamira commercial fleet — modern geared general cargo carriers (MV MOLPADIA, MV METANIRA) with 2x30MT cranes and box-shaped holds for direct charter fixtures.",
      ua: "Комерційний флот Danamira — сучасні суховантажні судна з кранами 2x30MT.",
      ru: "Коммерческий флот Danamira — современные сухогрузные суда с кранами 2x30MT.",
    },
    content: {
      en: "<h1>Commercial Managed Fleet &amp; Technical Specifications</h1><p>Explore our active fleet of geared general cargo and dry bulk carriers available for worldwide voyage and time charter employment.</p><h2>Fleet Standards &amp; Capabilities</h2><ul><li><strong>Geared Versatility:</strong> High-capacity electro-hydraulic cranes (2x 30MT SWL) for self-sustained loading and discharging at unequipped berths.</li><li><strong>Box-Shaped Cargo Holds:</strong> Optimized for steel products, large timber packages, bulk minerals, and project equipment.</li><li><strong>Classification &amp; Flag:</strong> Top-tier IACS Classification (Lloyd's Register) and reputable Flag State administration.</li></ul>",
      ua: "",
      ru: "",
    },
    createdAt: new Date().toISOString(),
  },
  {
    id: "page-company",
    slug: "company.html",
    pageName: "About Company",
    status: "published",
    includeInNav: true,
    title: {
      en: "About Company & Maritime Framework | Danamira Shipping",
      ua: "Про компанію та морські стандарти | Danamira",
      ru: "О компании и морские стандарты | Danamira",
    },
    metaDescription: {
      en: "Maritime tradition, technical excellence, and ISM/ISPS safety compliance. Danamira Shipping delivers dependable global sea transport services.",
      ua: "Морські традиції, технічна досконалість та безпека ISM/ISPS.",
      ru: "Морские традиции, техническое совершенство и безопасность ISM/ISPS.",
    },
    content: {
      en: "<h1>Integrated Ship Management &amp; Maritime Excellence</h1><p><strong>DANAMIRA SHIPPING LTD</strong> is an independent ship-management company registered in Liberia with its official Greek Branch established in Glyfada, Greece, operating under the Greek maritime framework of <strong>Law 89/1967</strong>.</p><p>We provide integrated ship management services covering commercial management, sale &amp; purchase (S&amp;P), chartering, vessel operations, technical management, ISM &amp; safety management, as well as comprehensive financial support.</p><h2>Mission Statement: Focused Dry Bulk Management</h2><p>Danamira Shipping focuses on the dry cargo market, primarily managing and operating general cargo and bulk carrier vessels. Our commercial team actively evaluates voyage and time charter opportunities across international trading areas, while our operation and technical departments provide continuous 24/7 support throughout each vessel's employment.</p><h2>Corporate Vision &amp; Strategic Growth</h2><p>Long-term development through strategic fleet expansion and continuous growth of the Company’s maritime operations. Future plans include the active consideration of newbuilding projects, energy-efficient hull designs, and advanced green construction standards.</p><h2>Operating Trade Basins</h2><ul><li>Black Sea &amp; Sea of Azov</li><li>Mediterranean Sea &amp; Adriatic Sea</li><li>Baltic Sea &amp; North Sea</li><li>European Continent &amp; Scandinavian Ports</li><li>West Africa, USA Gulf &amp; Caribbean Sea</li></ul><h2>Dry Bulk Cargo Portfolio</h2><ul><li><strong>Agribulk Cargoes:</strong> Wheat, Corn, Barley, Soybeans, Sunflower Seeds &amp; Meals.</li><li><strong>Solid Bulk Chemicals:</strong> Urea, Ammonium Nitrate, Phosphates, Potash &amp; Compound Fertilizers.</li><li><strong>Metallic &amp; Mineral Cargoes:</strong> Pig Iron, Hot Briquetted Iron (HBI), Scrap Steel, Steel Coils, Billets, Rebars &amp; Clinker.</li></ul>",
      ua: "",
      ru: "",
    },
    createdAt: new Date().toISOString(),
  },
  {
    id: "page-careers",
    slug: "careers.html",
    pageName: "Careers & Crewing",
    status: "published",
    includeInNav: true,
    title: {
      en: "Careers, Seafarer Recruitment & Crewing | Danamira Shipping",
      ua: "Кар'єра, працевлаштування моряків та крюїнг | Danamira",
      ru: "Карьера, трудоустройство моряков и крюинг | Danamira",
    },
    metaDescription: {
      en: "Join the Danamira maritime team. Shore-based career opportunities and vessel crew placements for qualified officers and ratings.",
      ua: "Вакансії для моряків та берегових спеціалістів у флоті Danamira.",
      ru: "Вакансии для моряков и береговых специалистов во флоте Danamira.",
    },
    content: {
      en: "<h1>Maritime Careers &amp; Seafarer Recruitment</h1><p>Join the <strong>DANAMIRA SHIPPING LTD</strong> maritime team. We offer long-term sea careers on modern geared general cargo carriers and shore-based technical positions at our Greek and international offices.</p><h2>Vessel Crew Opportunities</h2><ul><li><strong>Deck Officers:</strong> Master Mariner, Chief Officer, Second &amp; Third Officers.</li><li><strong>Engine Officers:</strong> Chief Engineer, Second Engineer, Electrical Engineer.</li><li><strong>Deck &amp; Engine Ratings:</strong> Bosun, Able Seaman (AB), Motorman, Fitter/Welder, Cook.</li></ul><h2>Crew Welfare &amp; Employment Benefits</h2><ul><li>Competitive salary packages in USD according to ITF international standards.</li><li>Regular contract rotations with reliable on-time crew changes.</li><li>Full P&amp;I medical and emergency health insurance coverage.</li><li>Modern vessel accommodations, onboard satellite communications, and safety gear.</li></ul>",
      ua: "",
      ru: "",
    },
    createdAt: new Date().toISOString(),
  },
  {
    id: "page-contact",
    slug: "contact.html",
    pageName: "Global Offices & Contact",
    status: "published",
    includeInNav: true,
    title: {
      en: "Global Offices & Direct Chartering Inquiries | Danamira Shipping",
      ua: "Офіси у світі та прямі контакти чартерингу | Danamira",
      ru: "Офисы в мире и прямые контакты чартеринга | Danamira",
    },
    metaDescription: {
      en: "Contact Danamira Shipping chartering desk, vessel operations, and branch offices in Dubai, Istanbul, Odesa, and Athens.",
      ua: "Контакти відділу чартерингу та офісів у Дубаї, Стамбулі, Одесі та Афінах.",
      ru: "Контакты отдела чартеринга и офисов в Дубае, Стамбуле, Одессе и Афинах.",
    },
    content: {
      en: "<h1>Global Offices &amp; Commercial Inquiries</h1><p>Contact the <strong>DANAMIRA SHIPPING LTD</strong> chartering desk, vessel operations, and branch office network for prompt vessel fixtures and freight rate indications.</p><h2>Operational Head Office (Greek Branch)</h2><p><strong>Address:</strong> Zeppou 33, 166 75 Glyfada, Athens, Greece (Law 89/1967)<br /><strong>Telephone:</strong> +30 211 34 56 550<br /><strong>Email:</strong> chartering@danamira-shipping.com</p><h2>24/7 Emergency &amp; Operational Response</h2><p>Our dedicated operations team monitors vessel traffic, weather routing, and port agents 24 hours a day, 7 days a week.</p>",
      ua: "",
      ru: "",
    },
    createdAt: new Date().toISOString(),
  },
  {
    id: "page-privacy",
    slug: "privacy.html",
    pageName: "Privacy Policy",
    status: "published",
    includeInNav: false,
    title: {
      en: "Privacy Policy & Data Protection | Danamira Shipping",
      ua: "Політика конфіденційності | Danamira",
      ru: "Политика конфиденциальности | Danamira",
    },
    metaDescription: {
      en: "Danamira Shipping Ltd commitment to data protection, GDPR compliance, and client confidential information security.",
      ua: "Захист персональних даних та конфіденційність інформації клієнтів.",
      ru: "Защита персональных данных и конфиденциальность информации клиентов.",
    },
    content: {
      en: "<h1>Privacy Policy &amp; Data Protection</h1><p><strong>DANAMIRA SHIPPING LTD</strong> is committed to protecting the privacy, confidentiality, and security of all personal and commercial information collected through our website and chartering communication channels.</p><h2>Information We Collect</h2><p>We only collect information necessary to process sea freight inquiries, vessel charter applications, and crew recruitment submissions (such as company name, contact person, email, telephone number, and cargo details).</p><h2>Data Security &amp; Confidentiality</h2><p>All data is processed strictly in accordance with GDPR principles and international maritime data security standards. We never sell, rent, or disclose client or applicant data to third parties.</p>",
      ua: "",
      ru: "",
    },
    createdAt: new Date().toISOString(),
  },
  {
    id: "page-terms",
    slug: "terms.html",
    pageName: "Terms & Conditions",
    status: "published",
    includeInNav: false,
    title: {
      en: "Terms & Conditions of Service | Danamira Shipping",
      ua: "Умови використання та надання послуг | Danamira",
      ru: "Условия использования и предоставления услуг | Danamira",
    },
    metaDescription: {
      en: "Terms and conditions governing the use of Danamira Shipping digital services, charter inquiries, and website information.",
      ua: "Умови користування сервісами та сайтом Danamira Shipping.",
      ru: "Условия пользования сервисами и сайтом Danamira Shipping.",
    },
    content: {
      en: "<h1>Terms &amp; Conditions of Service</h1><p>These terms govern the use of the <strong>DANAMIRA SHIPPING LTD</strong> website, vessel particulars information, and charter rate inquiry services.</p><h2>Chartering Inquiries &amp; Fixture Terms</h2><p>All vessel availability, cargo freight indications, and vessel specifications provided on this website are for preliminary guidance only and are subject to final contract negotiation and fixture confirmation via official charter party agreements (e.g. GENCON / NYPE).</p><h2>Intellectual Property &amp; Particulars Accuracy</h2><p>Vessel particulars, GA-plans, technical drawings, and company trademarks remain the exclusive property of Danamira Shipping Ltd.</p>",
      ua: "",
      ru: "",
    },
    createdAt: new Date().toISOString(),
  },
];

export const sampleBranches = [
  {
    id: "branch-001",
    name: "Operational Head Office (Greek Branch)",
    portCity: "Glyfada, Athens",
    country: "Greece",
    address: "Zeppou 33, 166 75 Glyfada, Greece",
    phone: "+30 211 34 56 550",
    email: "chartering@danamira-shipping.com",
    agentName: "Capt. Operations / Law 89/1967",
    sortOrder: 1,
  },
  {
    id: "branch-002",
    name: "Black Sea Agency Office",
    portCity: "Odesa",
    country: "Ukraine",
    address: "Prymorska St 6, Odesa 65000",
    phone: "+380 48 7001234",
    email: "odesa@danamira-shipping.com",
    agentName: "Dmitry Kovalenko",
    sortOrder: 2,
  },
  {
    id: "branch-003",
    name: "North Europe Commercial Office",
    portCity: "Rotterdam",
    country: "Netherlands",
    address: "Wilhelminakade 123, 3072 AP Rotterdam",
    phone: "+31 10 9876543",
    email: "rotterdam@danamira-shipping.com",
    agentName: "Jan van den Berg",
    sortOrder: 3,
  },
  {
    id: "branch-004",
    name: "Middle East Logistics Agency",
    portCity: "Dubai",
    country: "UAE",
    address: "JAFZA One, Jebel Ali Free Zone, Dubai",
    phone: "+971 4 8812345",
    email: "dubai@danamira-shipping.com",
    agentName: "Tariq Al-Mansoor",
    sortOrder: 4,
  },
];
